// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
package Nicoli.IngDelSw.model;
/************************************************************/
/**
 * 
 */
public class BaselineVisit extends Visit {
}
