// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

/************************************************************/
package Nicoli.IngDelSw.model;
/**
 * 
 */
public class Localization {
	/**
	 * 
	 */
	public String name;
	/**
	 * 
	 */
	public int localization_id;
	/**
	 * 
	 */
	public Gender gender;
	/**
	 * 
	 */
	public String description;
	/**
	 * 
	 */
	public LocalizationView[] localizationview;
}
