// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

/************************************************************/
package Nicoli.IngDelSw.model;
/**
 * 
 */
public class LocalizationView {
	/**
	 * 
	 */
	public int location_id;
	/**
	 * 
	 */
	public int id;
	/**
	 * 
	 */
	public String name;
	/**
	 * 
	 */
	public int order;
	/**
	 * 
	 */
	public Photos photos;

	/**
	 * 
	 */
	public void localizations() {
	}
}
