// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

/************************************************************/
package Nicoli.IngDelSw.model;
import java.time.LocalDate;
/**
 * 
 */
public class Patient extends User {
	/**
	 * 
	 */
	public int created_by;
	/**
	 * 
	 */
	public LocalDate date_of_birth;
	/**
	 * 
	 */
	public String ethnicity;
	/**
	 * 
	 */
	public String previous_history;
	/**
	 * 
	 */
	public Visit[] visit;
}
