// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

/************************************************************/
package Nicoli.IngDelSw.model;
/**
 * 
 */
public class Photos {
	/**
	 * 
	 */
	public int id;
	/**
	 * 
	 */
	public int visit_id;
	/**
	 * 
	 */
	public String image;
	/**
	 * 
	 */
	public int localization_view_id;
	/**
	 * 
	 */
	public String status;
	/**
	 * 
	 */
	public String rejected_note;
}
