// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

/************************************************************/
package Nicoli.IngDelSw.model;
/**
 * 
 */
public class Products {
	/**
	 * 
	 */
	public int product_id;
	/**
	 * 
	 */
	public String product_name;
	/**
	 * 
	 */
	public TreatedArea treatedarea;
}
