// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

/************************************************************/
package Nicoli.IngDelSw.model;
/**
 * 
 */
public class ProductsVisits {
	/**
	 * 
	 */
	public int visit_id;
	/**
	 * 
	 */
	public int product_id;
}
