// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

/************************************************************/
package Nicoli.IngDelSw.model;
/**
 * 
 */
public class TreatedArea {
	/**
	 * 
	 */
	public int id;
	/**
	 * 
	 */
	public int visit_id;
	/**
	 * 
	 */
	public String area;
	/**
	 * 
	 */
	public int localization_view_id;
	/**
	 * 
	 */
	public int product_id;
	/**
	 * 
	 */
	public int dosage;
	/**
	 * 
	 */
	public int photo_id;
	/**
	 * 
	 */
	public double point_top;
	/**
	 * 
	 */
	public double point_left;
	/**
	 * 
	 */
	public Photos[] photos;
	/**
	 * 
	 */
	public LocalizationView[] localizationview;

	/**
	 * 
	 */
	public void photo() {
	}

	/**
	 * 
	 */
	public void product() {
	}
}
