// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

/************************************************************/
package Nicoli.IngDelSw.model;
/**
 * 
 */
public class Treatment {
	/**
	 * 
	 */
	public int patient_id;
	/**
	 * 
	 */
	public String motivation_title;
	/**
	 * 
	 */
	public String motivation_desc;
	/**
	 * 
	 */
	public int localization_id;
	/**
	 * 
	 */
	public int last_visit_id;
	/**
	 * 
	 */
	public int treatment_id;
	/**
	 * 
	 */
	public Visit[] visit;

	/**
	 * 
	 */
	public void visits() {
	}
}
