// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

/************************************************************/
package Nicoli.IngDelSw.model;
/**
 * 
 */
public class TreatmentVisit extends Visit{
	/**
	 * 
	 */
	public TreatedArea[] treatedarea;

	/**
	 *
	 */
	public void products() {
	}
}
