// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Nicoli.IngDelSw.model;
/************************************************************/

import java.time.LocalDateTime;

/**
 *
 */
public class User {
	/**
	 * 
	 */
	public int id;
	/**
	 * 
	 */
	public String password;
	/**
	 * 
	 */
	public String first_name;
	/**
	 * 
	 */
	public String last_name;
	/**
	 * 
	 */
	public Gender gender;
	/**
	 * 
	 */
	public Role role;
	/**
	 * 
	 */
	public LocalDateTime email_verified_at;
	/**
	 * 
	 */
	public LocalDateTime activated_at;
	/**
	 * 
	 */
	public String email;
	/**
	 * 
	 */
	public Visit[] visit;

	/**
	 * 
	 */
	public void isAdmin() {
	}

	/**
	 * 
	 * @param role 
	 */
	public void hasRole(Role role) {
	}

	/**
	 * 
	 */
	public void isUser() {
	}

	/**
	 * 
	 */
	public void isMedic() {
	}
}
